services:
  db:
    image: mysql:8.1
    container_name: assignment-2-webcrafters-db-1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_DATABASE: cmsdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot12345"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: chong0508/confease-backend:latest
    container_name: assignment-2-webcrafters-backend-1
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cmsdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root12345
    command: java -jar /app.jar
    volumes:
      - ./uploads:/app/uploads

  jenkins:
    build:
      context: .
      dockerfile: backend/jenkins.DockerFile
    privileged: true
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  frontend:
    image: hazimharon230/conf-frontend:v0.1.1
    container_name: assignment-3-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist/frontend/browser:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

volumes:
  mysql_data:
  jenkins_data:
